version: "3.4"
services:
  app:
    container_name: react-alarm
    image: react-alarm
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000